### ISSUE TITLE
mvn repo for 2.4.1

### ISSUE THREAD

**Issue by emiguelt** [lucaspouzac/contiperf#8]
Hi, I would like to use the library in a project, is the 2.4.1 version available in any public repository?

Thanks,

Edwin Miguel

**Comment by fdw** [comment]
I'm interested in this as well. Why is there only a 2.3.4 version available at Maven Central, but no 2.4.x?

**Comment by NicoK** [comment]
same for 2.4.3... there are only old versions at maven central :(
https://search.maven.org/#search|gav|1|g%3A%22org.databene%22%20AND%20a%3A%22contiperf%22

**Comment by lbesuchet** [comment]
also waiting for 2.4.3 at maven central ...

**Comment by noconnor** [comment]
+1

**Comment by fdw** [comment]
Any news on this? Or has development stopped?

**Comment by twillouer** [comment]
:+1:

**Comment by pethers** [comment]
Also waiting for  2.4.3 at maven central or any other public repo.

**Comment by lucaspouzac** [comment]
Hi

This repo will be removed, unless someone wants to recover its management (end 2015).

I recommend using JMH.

**Comment by tomdesair** [comment]
@lucaspouzac Would it be possible to push the latest release to the Maven repositories before stopping the project?

**Comment by javatlacati** [comment]
Perhaps you could try using [jitpack as repository](https://jitpack.io/#lucaspouzac/contiperf).

**Comment by javatlacati** [comment]
Please try [version 2.4.3](https://mvnrepository.com/artifact/com.github.javatlacati/contiperf/2.4.3) instead

**Comment by tomdesair** [comment]
Thanks for the update @javatlacati !
